/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uCLQ1Acak8X
 */
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function CardsSection() {
  return (
    <div key="1" className="bg-[#f4f1ee]">
      <section className="container mx-auto my-6 grid grid-cols-1 gap-4 md:grid-cols-3">
        <Card className="w-full bg-white">
          <img
            alt="Store 1"
            className="h-48 w-full object-cover"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/200",
              objectFit: "cover",
            }}
            width="300"
          />
          <CardContent>
            <h2 className="text-lg font-bold">Store Name 1</h2>
            <p className="text-sm">Address details here</p>
          </CardContent>
          <CardFooter className="flex justify-end">
            <Button className="bg-[#a67c52] text-white">Buy</Button>
          </CardFooter>
        </Card>
        <Card className="w-full bg-white">
          <img
            alt="Store 2"
            className="h-48 w-full object-cover"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/200",
              objectFit: "cover",
            }}
            width="300"
          />
          <CardContent>
            <h2 className="text-lg font-bold">Store Name 2</h2>
            <p className="text-sm">Address details here</p>
          </CardContent>
          <CardFooter className="flex justify-end">
            <Button className="bg-[#a67c52] text-white">Buy</Button>
          </CardFooter>
        </Card>
        <Card className="w-full bg-white">
          <img
            alt="Store 3"
            className="h-48 w-full object-cover"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "300/200",
              objectFit: "cover",
            }}
            width="300"
          />
          <CardContent>
            <h2 className="text-lg font-bold">Store Name 3</h2>
            <p className="text-sm">Address details here</p>
          </CardContent>
          <CardFooter className="flex justify-end">
            <Button className="bg-[#a67c52] text-white">Buy</Button>
          </CardFooter>
        </Card>
      </section>
    </div>
  )
}
