/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CvAt4gNrM9b
 */
import Image from "next/image";
import { Button } from "./ui/button";

export function HeroComponent() {
  return (
    <div className="h-screen w-full bg-[#2c0e09] text-[#372727]">
      <div className="container h-full space-y-6 py-12  md:grid md:items-center md:space-y-0 md:py-24 lg:grid-cols-2 lg:space-y-0">
        <div className="flex flex-col items-center justify-center space-y-4 lg:order-1 lg:items-start lg:px-20">
          <Image
            alt="Logo"
            className="overflow-hidden "
            src="/logo_cacau_show.svg"
            width="600"
            height="150"
            priority
          />
          <div className="space-y-2 text-center text-[#b0d67a] lg:text-left">
            <a
              href="https://www.instagram.com/lojacacaushow.recife"
              className="text-2xl font-bold tracking-tighter sm:text-3xl"
              target="_blank"
            >
              @lojacacaushow.recife
            </a>
          </div>
        </div>
        <div className="flex flex-col items-center justify-center space-y-4 lg:order-1 lg:items-start lg:px-20">
          <p className=" max-w-[500px] text-left text-gray-200 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Principal rede de franquias da cacau show de Recife.
          </p>
          <ul className="list-inside list-disc self-start text-gray-200 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Lojas: (clique para abrir no mapa)
            <li className="hover:underline">
              <a
                href="https://maps.app.goo.gl/rxXv4QKUi4dcq613A"
                target="_blank"
              >
                Plaza Shopping
              </a>
            </li>
            <li className="hover:underline">
              <a
                href="https://maps.app.goo.gl/TywBiMbPiYqyw4LE7"
                target="_blank"
              >
                Boa viagem
              </a>
            </li>
            <li className="hover:underline">
              <a
                href="https://maps.app.goo.gl/yumB6vitwDixAyri7"
                target="_blank"
              >
                Casa Amarela
              </a>
            </li>
            <li className="hover:underline">
              <a
                href="https://maps.app.goo.gl/qQaK6u99SmssfPi66"
                target="_blank"
              >
                Graças
              </a>
            </li>
            <li className="hover:underline">
              <a
                href="https://maps.app.goo.gl/pWBF6C3GmJvUrYs28"
                target="_blank"
              >
                Caxangá
              </a>
            </li>
            <li className="hover:underline">
              <a
                href="https://maps.app.goo.gl/YyTRGZB1xzwSNbT48"
                target="_blank"
              >
                Tamarineira
              </a>
            </li>
          </ul>
          <div className="flex items-center justify-center space-x-4 lg:order-1 lg:items-end lg:justify-start">
            <a
              className="flex h-10 items-center rounded-md bg-gray-50 px-4 text-sm font-medium shadow transition-colors hover:bg-gray-50/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
              href="https://www.instagram.com/lojacacaushow.recife"
              target="_blank"
            >
              <InstagramIcon className="mr-1 h-4 w-4" />
              Seguir
            </a>
            <a
              className="flex h-10 items-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:border-gray-800  dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
              href="https://linktr.ee/cacaushow.recife"
              target="_blank"
            >
              <SmartphoneIcon className="mr-1 h-4 w-4" />
              Pedir agora
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function SmartphoneIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  );
}
